/**
 * Shared template strings and builder functions used across generators.
 * Centralised here to keep layout patterns consistent and DRY.
 */

import { type FontConfig, DEFAULT_FONT_CONFIG } from "../constants/font-map.js";

const META_DESCRIPTION = 'Generated by Monoframe';

/**
 * Converts a kebab-case app name to a display name.
 * Example: "my-app" → "My App"
 */
export function toDisplayName(appName: string): string {
  return appName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Derive a camelCase variable name from the font import name.
 * E.g. "JetBrains_Mono" → "jetBrainsMono", "Inter" → "inter"
 */
function toFontVarName(importName: string): string {
  return importName
    .split('_')
    .map((part, index) =>
      index === 0
        ? part.toLowerCase()
        : part.charAt(0).toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join('');
}

/**
 * Build the root layout.tsx content for a Next.js app.
 *
 * Dynamically imports the correct font based on the user's shadcn preset
 * and wraps children in ThemeProvider when shadcn is enabled.
 *
 * The body tag follows a consistent pattern that animations.ts can match:
 *   <body className={`${fontVar.variable} antialiased`}>
 */
export function buildLayoutTemplate(
  displayName: string,
  fontConfig: FontConfig = DEFAULT_FONT_CONFIG,
  hasShadcn: boolean = false,
): string {
  const fontVarName = toFontVarName(fontConfig.importName);

  const fontImport = `import { ${fontConfig.importName} } from '${fontConfig.importPackage}';`;

  const themeProviderImport = hasShadcn
    ? `import { ThemeProvider } from '@repo/ui';\n`
    : '';

  const suppressHydration = hasShadcn ? ' suppressHydrationWarning' : '';

  const childrenWrapped = hasShadcn
    ? `<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>`
    : '{children}';

  return `import type { Metadata } from 'next';
${fontImport}
${themeProviderImport}import './globals.css';

const ${fontVarName} = ${fontConfig.importName}({
  subsets: ['latin'],
  variable: '${fontConfig.cssVariable}',
});

export const metadata: Metadata = {
  title: '${displayName}',
  description: '${META_DESCRIPTION}',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"${suppressHydration}>
      <body className={\`\${${fontVarName}.variable} antialiased\`}>
        ${childrenWrapped}
      </body>
    </html>
  );
}
`;
}
