/**
 * Shared template strings and builder functions used across generators.
 * Centralised here to keep layout patterns consistent and DRY.
 */

const META_DESCRIPTION = 'Generated by Monoframe';

/**
 * Converts a kebab-case app name to a display name.
 * Example: "my-app" → "My App"
 */
export function toDisplayName(appName: string): string {
  return appName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Build the root layout.tsx content for a Next.js app.
 *
 * Uses the industry-standard CSS variable font approach recommended by
 * Vercel and shadcn docs: `fontSans.variable` on the body tag with
 * `antialiased` for smooth font rendering.
 *
 * The body tag follows a consistent pattern that animations.ts can match:
 *   <body className={`${fontSans.variable} antialiased`}>
 */
export function buildLayoutTemplate(displayName: string): string {
  return `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: '${displayName}',
  description: '${META_DESCRIPTION}',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={\`\${fontSans.variable} antialiased\`}>{children}</body>
    </html>
  );
}
`;
}
